Repository konveyor/tackle-test-generator-cli, pull requests merged in 2021-12, with the labels that each got.

#129 fixed usage of java_jdk_home option
  README.md
  tkltest/generate/generate.py
  tkltest/util/config_options.py
Labels: fix

#133 Publish tkltest docker image to GitHub container registry on release
  .github/workflows/release.yml
Labels: enhancement

#132 Issue 84 create classpath file
  .github/workflows/python_test.yml
  README.md
  doc/user_guide.md
  test/data/84_ifx-framework/build.properties
  test/data/84_ifx-framework/build.xml
  test/data/84_ifx-framework/ifx-frameworkMonoClasspath.txt
  test/data/84_ifx-framework/lib/jdom.jar
  test/data/84_ifx-framework/lib/poolman.jar
  test/data/84_ifx-framework/lib/velocity-dep-1.4.jar
  test/data/84_ifx-framework/lib/xercesImpl.jar
  test/data/84_ifx-framework/tkltest_config.toml
  test/data/irs/monolith/build.xml
  test/test_unit_tests.py
  tkltest/util/config_options.py
  tkltest/util/config_util.py
Labels: enhancement

#136 Issue 115 create classpath from maven build file
  README.md
  doc/user_guide.md
  test/data/14_spark/pom.xml
  test/data/14_spark/sparkMonoClasspath.txt
  test/data/14_spark/tkltest_config.toml
  test/data/3_scribe-java/3_scribe-javaMonoClasspath.txt
  test/data/3_scribe-java/pom.xml
  test/data/3_scribe-java/tkltest_config.toml
  test/data/splitNjoin/splitNjoinMonoClasspath.txt
  test/test_generate_execute.py
  test/test_unit_tests.py
  tkltest/util/config_options.py
  tkltest/util/config_util.py
  tkltest/util/constants.py
Labels: enhancement

#140 Support maven build type in test augmentation
  tkltest/util/coverage_util.py
Labels: fix

#142 Fixes to maven build file for correct execution and report creation
  tkltest/util/build_util.py
Labels: fix

#144 Readme update
  README.md
  tkltest/_version.py
Labels: documentation
