Repository konveyor/tackle-test-generator-cli, pull requests merged in 2022-03, with the labels that each got.

#210 Optionally generate bad path test cases
  doc/tkltest_unit_config_options.md
  test/data/failingApp/classpath.txt
  test/data/failingApp/pom.xml
  test/data/failingApp/src/main/java/failing/Failing.java
  test/data/failingApp/target/classes/failing/Failing.class
  test/data/failingApp/tkltest_config.toml
  test/unit/test_generate_execute.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/util/config_util.py
  tkltest/util/unit/config_options_unit.py
Labels: enhancement

#214 Tkltest UI doc
  README.md
  doc/installation.md
  doc/ui/quick_start_guide.md
  doc/ui/tkltest_ui_config_options.md
  doc/ui/user_guide.md
  doc/unit/images/ctd_coverage_report.png
  doc/unit/images/ctd_coverage_report_methods.png
  doc/unit/images/jacoco_report.png
  doc/unit/images/junit_report.png
  doc/unit/quick_start_guide.md
  doc/unit/tkltest_unit_config_options.md
  doc/unit/user_guide.md
Labels: documentation

#218 Preserve dependency jars order when analyzing ant build files
  test/data/84_ifx-framework/build.xml
  test/data/irs/monolith/for_tests_build.xml
  test/unit/test_unit_tests.py
  tkltest/util/config_util.py
  tkltest/util/constants.py
Labels: fix

#228 Fixed exclusion of generate option on config init
  tkltest/util/unit/config_options_unit.py
Labels: fix

#230 Make maximal number of discovered action explorations configurable
  doc/installation.md
  doc/ui/tkltest_ui_config_options.md
  test/ui/data/addressbook/tkltest_ui_config.toml
  test/ui/data/petclinic/tkltest_ui_config.toml
  test/ui/tkltest_ui_config.toml
  tkltest/generate/ui/generate.py
  tkltest/util/ui/config_options_ui.py
Labels: enhancement

#232 Support Java 11
  .github/workflows/release.yml
  doc/installation.md
  doc/unit/tkltest_unit_config_options.md
  lib/download_lib_jars.sh
  lib/pom.xml
  test/data/irs/user-tests/build.gradle
  test/data/irs/user-tests/build.xml
  test/data/splitNjoin/user-tests/build.gradle
  tkltest/_version.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/util/constants.py
  tkltest/util/unit/config_options_unit.py
  tkltest/util/unit/dir_util.py
Labels: enhancement, tkltest-unit

#233 Use user's provided java in execution of generated build files
  lib/pom.xml
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/augment.py
  tkltest/generate/unit/generate.py
  tkltest/util/unit/coverage_util.py
Labels: fix, tkltest-unit
