Repository konveyor/tackle-test-generator-cli, pull requests merged in 2022-02, with the labels that each got.

#177 Util refactoring and UI config updates
  .github/workflows/tkltest_ui_ci.yml
  .github/workflows/tkltest_unit_ci.yml
  test/unit/test_generate_execute.py
  test/unit/test_unit_tests.py
  tkltest/execute/unit/compare_coverage.py
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/augment.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/tkltest_ui.py
  tkltest/tkltest_unit.py
  tkltest/util/config_options.py
  tkltest/util/config_util.py
  tkltest/util/ui/__init__.py
  tkltest/util/ui/config_options_ui.py
  tkltest/util/unit/__init__.py
  tkltest/util/unit/build_template.gradle
  tkltest/util/unit/build_util.py
  tkltest/util/unit/code_util.py
  tkltest/util/unit/config_options_unit.py
  tkltest/util/unit/coverage_util.py
  tkltest/util/unit/dir_util.py
  tkltest/util/unit/java_class_parser.py
Labels: refactoring

#179 Integrate core updates for refinements in assertion generation
  lib/pom.xml
  tkltest/generate/unit/generate.py
  tkltest/util/constants.py
Labels: enhancement

#194 Generate and execute a separate test suite for each app module
  doc/tkltest_unit_config_options.md
  test/data/14_spark/tkltest_config.toml
  test/data/3_scribe-java/tkltest_config.toml
  test/data/84_ifx-framework/tkltest_config.toml
  test/data/irs/tkltest_config_err2.toml
  test/data/irs/tkltest_config_err3.toml
  test/data/splitNjoin/tkltest_config.toml
  test/data/windup-sample/tkltest_config_web.toml
  test/unit/test_cli.bats
  test/unit/test_cli_irs.bats
  test/unit/test_generate_execute.py
  test/unit/test_unit_tests.py
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/tkltest_unit.py
  tkltest/util/config_util.py
  tkltest/util/unit/build_util.py
  tkltest/util/unit/config_options_unit.py
  tkltest/util/unit/dir_util.py
Labels: enhancement

#200 Directed test generation based on threshold of coverage achieved by developer tests
  README.md
  doc/tkltest_unit_config_options.md
  test/unit/test_unit_tests.py
  tkltest/_version.py
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/generate.py
  tkltest/util/config_options.py
  tkltest/util/constants.py
  tkltest/util/unit/config_options_unit.py
  tkltest/util/unit/coverage_util.py
Labels: enhancement

#201 Preserve dependencies order during gradle build file analysis
  test/data/splitNjoin/app/build/libs/app.jar
  test/data/splitNjoin/list/build/libs/list.jar
  test/data/splitNjoin/splitNjoinMonoClasspath.txt
  test/data/splitNjoin/utilities/build/libs/utilities.jar
  test/unit/test_unit_tests.py
  tkltest/util/config_util.py
Labels: fix
