Repository konveyor/tackle-test-generator-cli, pull requests merged in 2022-04, with the labels that each got.

#235 Integrate generated tests into application's maven build file
  doc/unit/user_guide.md
  test/data/windup-sample/windup-sample-web-ctd-amplified-tests/.tkltest_generate.toml
  test/data/windup-sample/windup-sample-web-ctd-amplified-tests/monolithic/com/acme/anvil/com_acme_anvil_AuthenticateFilter_Test.java
  test/data/windup-sample/windup-sample-web-ctd-amplified-tests/monolithic/com/acme/anvil/com_acme_anvil_LoginFilter_Test.java
  test/unit/test_unit_tests.py
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/util/unit/build_util.py
  tkltest/util/unit/dir_util.py
Labels: enhancement, tkltest-unit

#240 fix invalid cross device link error
  tkltest/util/unit/coverage_util.py
Labels: fix, tkltest-unit

#241 download evosuite jars with Dockerfile
  Dockerfile
Labels: fix, tkltest-unit

#244 Docker publish and doc updates
  .github/workflows/release.yml
  README.md
  doc/installation.md
  test/unit/test_cli_irs.bats
Labels: documentation

#247 Remove unsupported configuration options
  doc/unit/quick_start_guide.md
  doc/unit/tkltest_unit_config_options.md
  doc/unit/user_guide.md
  test/data/14_spark/tkltest_config.toml
  test/data/3_scribe-java/tkltest_config.toml
  test/data/84_ifx-framework/tkltest_config.toml
  test/data/daytrader7/tkltest_config.toml
  test/data/failingApp/tkltest_config.toml
  test/data/irs/irs-ctd-amplified-tests/.tkltest_generate.toml
  test/data/irs/tkltest_config.toml
  test/data/irs/tkltest_config2.toml
  test/data/irs/tkltest_config_err.toml
  test/data/irs/tkltest_config_err2.toml
  test/data/splitNjoin/splitNjoin-ctd-amplified-tests/.tkltest_generate.toml
  test/data/splitNjoin/tkltest_config.toml
  test/data/windup-sample/tkltest_config_web.toml
  test/data/windup-sample/windup-sample-web-ctd-amplified-tests/.tkltest_generate.toml
  test/unit/test_cli.bats
  test/unit/test_config.py
  test/unit/test_generate_execute.py
  test/unit/test_unit_tests.py
  tkltest/execute/unit/execute.py
  tkltest/generate/unit/generate.py
  tkltest/generate/unit/generate_standalone.py
  tkltest/util/config_util.py
  tkltest/util/unit/build_util.py
  tkltest/util/unit/config_options_unit.py
Labels: documentation, refactoring
